import '../downloads/download_item.dart';
import '../downloads/download_options.dart';

final initialMockDownloadItems = <DownloadItem>[
  DownloadItem(
    id: 'mock-1',
    title: 'Aula de viol\u00e3o \u2014 exemplo autorizado',
    durationLabel: '03:03',
    sizeLabel: '15,7 MB',
    formatLabel: 'MP4',
    qualityLabel: '480p',
    fpsLabel: '25fps',
    sourceLabel: 'Conte\u00fado autorizado',
    transferType: DownloadTransferType.video,
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-2',
    title: 'Clipe independente \u2014 Creative Commons',
    durationLabel: '03:03',
    sizeLabel: '20,8 MB',
    formatLabel: 'MP4',
    qualityLabel: '1080p',
    fpsLabel: '25fps',
    sourceLabel: 'Creative Commons',
    transferType: DownloadTransferType.video,
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-3',
    title: 'Podcast pr\u00f3prio \u2014 epis\u00f3dio teste',
    durationLabel: '31:12',
    sizeLabel: '96 MB',
    formatLabel: 'MP4',
    qualityLabel: '720p',
    fpsLabel: '30fps',
    sourceLabel: 'Conte\u00fado pr\u00f3prio',
    transferType: DownloadTransferType.audio,
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-4',
    title: 'Material de treino vocal \u2014 arquivo permitido',
    durationLabel: '03:14',
    sizeLabel: '9,3 MB',
    formatLabel: 'MP4',
    qualityLabel: '1080p',
    fpsLabel: '30fps',
    sourceLabel: 'Teste local',
    transferType: DownloadTransferType.video,
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
];
