import '../downloads/download_item.dart';

final initialMockDownloadItems = <DownloadItem>[
  DownloadItem(
    id: 'mock-1',
    title: 'Aula de violão — exemplo autorizado',
    durationLabel: '03:03',
    sizeLabel: '15,7 MB',
    formatLabel: 'MP4',
    qualityLabel: '480p',
    fpsLabel: '25fps',
    sourceLabel: 'Conteúdo autorizado',
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-2',
    title: 'Clipe independente — Creative Commons',
    durationLabel: '03:03',
    sizeLabel: '20,8 MB',
    formatLabel: 'MP4',
    qualityLabel: '1080p',
    fpsLabel: '25fps',
    sourceLabel: 'Creative Commons',
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-3',
    title: 'Podcast próprio — episódio teste',
    durationLabel: '31:12',
    sizeLabel: '96 MB',
    formatLabel: 'MP4',
    qualityLabel: '720p',
    fpsLabel: '30fps',
    sourceLabel: 'Conteúdo próprio',
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
  DownloadItem(
    id: 'mock-4',
    title: 'Material de treino vocal — arquivo permitido',
    durationLabel: '03:14',
    sizeLabel: '9,3 MB',
    formatLabel: 'MP4',
    qualityLabel: '1080p',
    fpsLabel: '30fps',
    sourceLabel: 'Teste local',
    status: DownloadStatus.completed,
    progress: 1.0,
  ),
];
